### ISSUE TITLE
tab-triggers not working in sublime

### ISSUE THREAD

**Issue by jt3k** [monkberry/language-monkberry#1]
![](https://i.imgur.com/aWEwmeE.gif)
reinstalling only for info that monkberry-plugin is installed

**Comment by antonmedv** [comment]
Ok, will try to figure out why this not working in sublime

**Comment by antonmedv** [comment]
It's looks like working for me:
![subl](https://cloud.githubusercontent.com/assets/141232/16645134/06e26bd8-444c-11e6-8453-8109c05c3bb6.gif)

**Comment by jt3k** [comment]
okay, I'll try a clean install sublimetext
